# Site settings
title: GADADHARA
description: "HOME INTERIOR DESIGN SOLUTIONS"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: GADADHARA
    hero_description: HOME INTERIOR DESIGN SOLUTIONS

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 9391 053 043
    emergency: 7981 985 906
    email: ajaykumarveera55@gmail.com
    address: hyderabad, pragathi nagar.
# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 13:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: hyderabad,pragathi nagar,india.
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2015 DentistSmile - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
